# ./rust-libs/Cargo.toml

[workspace]
members = [
    "calculator"
]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1.7"
